### PR TITLE
Llama3.1 Function Calling + New Tools

### PR DESCRIPTION
**Pull request by andthattoo**
### Add Meta-Llama Function Calling Pipeline and Integrate New Tools

Updates:

#### Meta-Llama Function Calling Pipeline:
Implemented a function calling pipeline for Llama3.1 models.

#### Tool Naming
Standardized tool names to use underscores.

#### Tests
Added several new tests to ensure functionality and reliability.

#### New Built-in Tools
Integrated serper and browserless as built-in tools.

These updates enhance the codebase by introducing a new function calling pipeline, improving naming consistency, expanding test coverage, and adding valuable new tools.

### CODE REVIEW

**Comment by andthattoo** [comment]
hey @pepperoni21
added llama3.1 function calling pipeline! Let me know when we can merge it :)

**Comment by erhant** [comment]
would love to see this merged 🙏🏻

**Comment by pepperoni21** [comment]
Will do later in the day! :)

**Comment by thisismz** [comment]
Add example for Llama 3.1 Function Calling and new tools

Please provide an example demonstrating the usage of the new Function Calling feature for Llama 3.1 and the newly added tools. This will help users understand how to implement and utilize these new capabilities in their projects.

**Comment by andthattoo** [comment]
hey @thisismz , there are examples in the [test](https://github.com/andthattoo/ollama-rs/blob/master/tests/function_call.rs) folder. We may add detailed examples once the detailed documentation is ready tho

**Pull request merged**
